### ISSUE TITLE
Make Shard code polymorphic over the symbol finite field

### ISSUE THREAD

**Issue by drskalman** [paritytech/rs-ec-perf#12]
shard need to be polymorphic in respect to the finite filed where the code symbols are defined over (not always two bytes). Moreover This code belong to the shard object:
   https://github.com/w3f/rs-ec-perf//blob/skalman-non-encoder-field/reed-solomon-novelpoly/src/novel_poly_basis/mod.rs#L117

**Comment by burdges** [comment]
We could dump Shard all together I think.  Ideally `FieldAdd` could've methods
```
fn to_bytes(x: [Self; 2]) -> [u8; 3] { .. }
fn from_bytes(x: [u8; 3]) -> [Self; 2] { .. }
```
except they could be simpler since we'll likely never support GF(2^12).  ;)

**Comment by drskalman** [comment]
hit a brick wall:
```
error: internal compiler error: compiler/rustc_middle/src/ich/impls_ty.rs:94:17: StableHasher: unexpected region '_#0r

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:1005:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (b663c0f4f 2021-05-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `[u8; _]: std::marker::Sized`
#1 [typeck] type-checking `novel_poly_basis::<impl at reed-solomon-novelpoly/src/novel_poly_basis/mod.rs:50:1: 436:2>::reconstruct`
end of query stack
error: aborting due to previous error; 13 warnings emitted

error: could not compile `reed-solomon-novelpoly`
```

**Comment by drskalman** [comment]
used associative const generic in f1b28f3 to prevent the compiler from crashing.
